export const START_LOADING = 'START_LOADING';
export const STOP_LOADING = 'STOP_LOADING';
export const SET_LAT_LONG = 'SET_LAT_LONG';
export const SET_HISTORY_LAT_LONG = 'SET_HISTORY_LAT_LONG';
export const SET_HISTORY = 'SET_HISTORY';
